name: Pipeline

on:
  push:
    branches: [ main ]
env:
  APPLICATION_NAME: startupapp

jobs:
  testci:
    runs-on: ubuntu-latest
    name: Job-CI
    steps:
    - uses: actions/checkout@v3     
    - name: Run pytest
      id: run_tests
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
      run: | 
        pip install --no-cache-dir --upgrade awscli boto3 pandas scikit-learn pytest 
        pytest
        
  submit_training_job:
    runs-on: ubuntu-latest
    name: Job-DeployPipeline
    needs: testci
    steps:
    - uses: actions/checkout@v3
    - name: Fire SageMaker
      id: sm_train
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        pip install --no-cache-dir --upgrade awscli boto3 sagemaker sagemaker[local] joblib s3fs fsspec 
        python pipeline_sample.py
